candyshop/candyshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("home.urls")),
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
    path('favoritos/', include('favoritos.urls')),    
    path('carrinho/', include('carrinho.urls')),
    path('perfil/', include('perfil.urls')),
    path('detalhesproduto/', include('detalhesproduto.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

candyshop/home/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.home, name='home'),
    path('acessardetalhes/<int:ProdutoCodigo>', views.acessardetalhes, name='acessardetalhes'),
    path('addfavorito/<int:ProdutoCodigo>', views.addfavorito, name='addfavorito'),
    path('addCarrinho/<int:ProdutoCodigo>', views.addCarrinho, name='addCarrinho'),
    path('search/', views.search, name='search'),
]

candyshop/perfil/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.perfil, name='perfil'),
    path('endereco/<int:endereco_id>/', views.endereco_view, name='endereco'),
    path('delete/<int:endereco_id>/', views.delete, name='delete'),
    
    path('add_endereco/<int:endereco_id>/', views.endereco_view, name='add_endereco'),
    path('get_cidades/<str:uf>/', views.get_cidades, name='get_cidades'),
    path('salvarPerfil/<int:perfil_id>/', views.salvarperfil, name='salvarPerfil')
]

candyshop/perfil/models.py
from django.db import models
from login.models import CustomUser
class Endereco(models.Model):
    ESTADOS_CHOICES = [
        ('12', 'Acre'),
        ('27', 'Alagoas'),
        ('16', 'Amapá'),
        ('13', 'Amazonas'),
        ('29', 'Bahia'),
        ('23', 'Ceará'),
        ('53', 'Distrito Federal'),
        ('32', 'Espírito Santo'),
        ('52', 'Goiás'),
        ('21', 'Maranhão'),
        ('51', 'Mato Grosso'),
        ('50', 'Mato Grosso do Sul'),
        ('31', 'Minas Gerais'),
        ('15', 'Pará'),
        ('25', 'Paraíba'),
        ('41', 'Paraná'),
        ('26', 'Pernambuco'),
        ('22', 'Piauí'),
        ('33', 'Rio de Janeiro'),
        ('24', 'Rio Grande do Norte'),
        ('43', 'Rio Grande do Sul'),
        ('11', 'Rondônia'),
        ('14', 'Roraima'),
        ('42', 'Santa Catarina'),
        ('35', 'São Paulo'),
        ('28', 'Sergipe'),
        ('17', 'Tocantins')
    ]


    rua = models.CharField(max_length=255)
    numero = models.IntegerField()
    cep = models.CharField(max_length=8)
    estado = models.CharField(max_length=2, choices=ESTADOS_CHOICES)
    cidade = models.CharField(max_length=255)
    complemento = models.CharField(max_length=255, blank=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)

candyshop/perfil/forms.py
from django import forms
from .models import Endereco
from login.models import CustomUser

class EnderecoForm(forms.ModelForm):
    class Meta:
        model = Endereco
        fields = ['rua', 'numero', 'cep', 'estado', 'cidade','complemento']


        

candyshop/perfil/views.py
from django.shortcuts import render,redirect, get_object_or_404
from login.models import CustomUser  # ou o nome do seu modelo de Perfil
from .forms import EnderecoForm
from .models import Endereco
import requests
from django.http import JsonResponse
from django.contrib import messages
from django.contrib.messages import constants

def perfil(request):
    user = CustomUser.objects.filter(email=request.user.email).first()
    if user:
        enderecos = user.endereco_set.all()
    return render(request, 'perfil.html', {'perfil': user, 'enderecos': enderecos})

def endereco_view(request, endereco_id=None):
    if endereco_id:
        endereco = get_object_or_404(Endereco, id=endereco_id)
    else:
        endereco = Endereco()

    form = EnderecoForm(request.POST or None, instance=endereco)

    if form.is_valid():
        endereco = form.save(commit=False)  # Não salve o formulário ainda
        endereco.user = request.user  # Defina o usuário do endereço como o usuário atual
        endereco.save()  # Agora salve o formulário
        messages.add_message(request, constants.SUCCESS,
                             'Endereço salvo com sucesso!')
        return redirect('perfil')  
        
    return render(request, 'add_enderecos.html', {'form': form,'endereco_id': endereco_id})


def get_cidades(request, uf):
    response = requests.get(f'https://servicodados.ibge.gov.br/api/v1/localidades/estados/{uf}/distritos')
    return JsonResponse(response.json(), safe=False)

def delete(request, endereco_id=None):
    try:
        endereco = get_object_or_404(Endereco, id=endereco_id)
        endereco.delete()
        messages.add_message(request, constants.SUCCESS,
                             'Endereço removido com sucesso!')
        return redirect('perfil')  
    except Endereco.DoesNotExist:
        messages.add_message(request, constants.ERROR,
                             'Falha ao remover o endereço, favor tentar novamente!')
        return redirect('perfil')  

def salvarperfil(request, perfil_id):
    if request.method == "POST":
        nome = request.POST.get('nome')
        sobrenome = request.POST.get('sobrenome')
        telefone = request.POST.get('telefone')
        email = request.POST.get('email')

        user = CustomUser.objects.filter(id=perfil_id).first()
        if user:
            user.username = nome
            user.sobrenome = sobrenome
            user.telefone = telefone
            user.email = email
            user.save()
            messages.add_message(request, constants.SUCCESS, 'Perfil atualizado com sucesso!')
        else:
            messages.add_message(request, constants.ERROR,
                             'Falha ao tentar atualizar o usuário, favor tente novamente!')
    return redirect('perfil') 
        

        
    

candyshop/perfil/templates/add_enderecos.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
<link rel="stylesheet" href="{% static 'home/css/home.css' %}">
<link rel="stylesheet" href="{% static 'perfil/css/add_endereco.css' %}">  <!-- Adicione o CSS do seu novo aplicativo aqui -->
{% endblock %}

{% block 'body' %}
<div class="centered-text">
    Endereço
</div>
{% if messages %}
{% for message in messages %}
<div class="alert {{message.tags}}" id="message">
    {{message}}
</div>
{% endfor %}
{% endif %}
<br>
<br>
<div class="endereco-container">
    <form method="POST" action="{% url 'add_endereco' endereco_id %}">
        
        {% csrf_token %}
        <div class="endereco-info">            
            <div class="endereco-info-group">
                <div>
                    <label>Rua:</label>
                    {{ form.rua }}
                </div>
                <div>
                    <label>Numero:</label>
                    {{ form.numero }}               
                </div>
            </div>
            <div class="endereco-info-group">
                <div>
                    <label>Cep:</label>
                    {{ form.cep }}
                </div>
                <div>
                    <label>Estado:</label>
                    {{ form.estado }}
                </div>
            </div>
            <div class="endereco-info-group">
                <div>
                    <label>Cidade:</label>                    
                    <select value-selected="{{ form.cidade.value }}" name="cidade" required="" id="id_cidade">
                    </select>
                </div>
            </div>
            <div class="endereco-info-group">
                <div id="complemento">
                    <label>Complemento:</label>                    
                    <textarea name="complemento" id="id_complemento" cols="30" rows="5" maxlength="255">{{ form.complemento.value }}</textarea>
                    
                </div>
            </div>            
        </div>            
        <input class="button-actions" type="submit" value="Salvar endereco">
    </form>
</div>
{% block 'javascript' %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
$(document).ready(function() {
    
    function buscaCidades(selecionado){
        var uf = $('#id_estado')[0].value;
        $.ajax({
            url: "/perfil/get_cidades/"+uf+"/",
            success: function(data) {
                var select = $('#id_cidade');
                select.empty();
                $.each(data, function(index, value) {
                    select.append('<option value="' + value.nome + '">' + value.nome + '</option>');
                });
            },
            complete: function(){
                if(selecionado != ''){
                    $('#id_cidade')[0].value = selecionado
                }
            }
        });
    }
    if($('#id_estado')[0].value != ''){
        //chama a function buscaCidades
        buscaCidades($('#id_cidade')[0].getAttribute('value-selected'));
    }
    $('#id_estado').change(function() {
        buscaCidades('');
    });

    
    
});
</script>
{% endblock %}
{% endblock %}

candyshop/perfil/templates/perfil.html
{% extends 'base.html' %} {% load static %} {% block 'head' %}
<link rel="stylesheet" href="{% static 'home/css/home.css' %}" />
<link rel="stylesheet" href="{% static 'perfil/css/perfil.css' %}" />
<!-- Adicione o CSS do seu novo aplicativo aqui -->
{% endblock %} {% block 'body' %}
<div class="centered-text">Perfil</div>
{% if messages %} {% for message in messages %}
<div class="alert {{message.tags}}" id="message">{{message}}</div>
{% endfor %} {% endif %}
<br />
<br />
<form method="POST" action="{% url 'salvarPerfil'  perfil.id  %}">
  {% csrf_token %}
  <div class="perfil-container">
    {% if perfil %}
    <!-- Substitua 'perfil' pelo nome do seu objeto de perfil -->
    <div class="perfil-info">
      <div class="perfil-info-group">
        <div>
          <p>Nome:</p>
          <input type="text" name="nome" value="{{ perfil.username }}" />
        </div>
        <div>
          <p>Sobrenome:</p>
          <input type="text" name="sobrenome" value="{{ perfil.sobrenome }}" />
        </div>
      </div>
      <div class="perfil-info-group">
        <div>
          <p>Telefone:</p>
          <input
            type="tel"
            name="telefone"
            id=""
            maxlength="20"
            value="{{ perfil.telefone }}"
          />
        </div>
        <div>
          <p>E-mail:</p>
          <input type="email" name="email" value="{{ perfil.email }}" />
        </div>
      </div>
      <!-- Adicione mais campos conforme necessário -->
      <div class="perfil-enderecos">
        <div class="perfil-info-group">
          <div id="enderecos">
            <p>Endereços:</p>
            {% for endereco in enderecos %}
            <div class="div-endereco">
              <div class="dados-endereco">
                <label class="rua">Rua {{endereco.rua}}</label>
                <label class="local"
                  >{{endereco.cidade}}, {{endereco.get_estado_display}}, CEP:
                  {{endereco.cep}}</label
                >
                <label class="local"
                  >Numero {{endereco.numero}}, {{endereco.complemento}}</label
                >
              </div>
              <div class="acoes-endereco">
                <a href="{% url 'endereco' endereco.id %}">
                  <img
                    id="edita-endereco"
                    class="acao-endereco"
                    src="{% static 'perfil/img/edit_icon.png' %}"
                  />
                </a>
                <br />
                <a href="{% url 'delete' endereco.id %}">
                  <img
                    id="deleta-endereco"
                    class="acao-endereco"
                    src="{% static 'perfil/img/deleted.png' %}"
                  />
                </a>
              </div>
            </div>
            {% endfor %}
            <div id="btn-novo-endereco">
              <a class="button-actions" href="{% url 'endereco' 0 %}">
                Adicionar novo endereço
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="perfil-acoes">
        <input class="button-actions" type="submit" value="Salvar Perfil" />
      </div>
      <div class="perfil-acoes">
        <a href="{% url 'sair' %}" class="button-actions">Sair</a>
    </div>

    {% else %}
    <br />
    <h1>Perfil não encontrado!</h1>
    {% endif %}
  </div>
</form>
{% endblock %}